name: Deploy Backend with Kamal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear known_hosts and trust server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Fully reset known hosts
          ssh-keygen -R apps.rubymonstas.ch || true
          ssh-keygen -R 116.203.85.111 || true

          # Trust the new keys (replace IP with your actual server if different)
          ssh-keyscan -H apps.rubymonstas.ch >> ~/.ssh/known_hosts
          ssh-keyscan -H 116.203.85.111 >> ~/.ssh/known_hosts

          # View the new fingerprint (debugging)
          ssh-keygen -lf ~/.ssh/known_hosts

          # Proactively test SSH
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa root@apps.rubymonstas.ch "echo SSH OK"



      - name: Install Ruby and Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Kamal
        run: gem install kamal

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v2

      - name: Deploy with Kamal
        env:
          KAMAL_REGISTRY_USERNAME: starshrimp
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          KAMAL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          kamal deploy

